zajecia 10 - zadanie 2
beattaa/JavaStart pull request #5
Opened 2020-05-10 13:24 UTC by beattaa

Nie wiem czemu przy danych 2 / 4600 jest odp:
You're trying to withdraw too high amount. You balance account is 3500.0 , so the withdrawing amount is 1100.0 too high
a potem dodatkowo:
null

2020-05-10 16:20 UTC, pawel-javastart requested changes
> Nie wiem czemu przy danych 2 / 4600 jest odp:
> You're trying to withdraw too high amount. You balance account is 3500.0 , so the withdrawing amount is 1100.0 too high
> a potem dodatkowo:
> null

poniewaz nie ustawilas pola message w swoich wyjatkach. Patrz kometarz w klasie `TooHighCreditAmountException`

2020-05-10 16:20 UTC, pawel-javastart commented on src/zajacia10/zadanie2/CashMachine.java
> +        try {
ten try-catch lepiej usunac( analogiczna sytuacja jak w zadaniu 10.1)

2020-05-10 16:20 UTC, pawel-javastart commented on src/zajacia10/zadanie2/CashMachine.java
> +        switch (getClientChoice()) {
mozesz rozwazyc umieszczenie calej insrukcji `switch` w jednym bloku `try-catch`. Tworzenie wielu blokow try catch sprawia ze kod jest mniej czytelny

2020-05-10 16:20 UTC, pawelkoperjavastart commented on src/zajacia10/zadanie2/TooHighCreditAmountException.java
> +        System.err.println("You're trying to withdraw too high amount. You balance account is " + balance + " " +
tutaj powinnas ustawic pole `message` przy uzyciu klasy nadrzednej
```
super("You're trying to withdraw too high amount. You balance account is " + balance + " " + ", so the withdrawing amount is " + (credit - balance) + " too high");
```

2020-05-10 16:20 UTC, pawelkoperjavastart commented on src/zajacia10/zadanie2/WithdrawMaxAmountException.java
> +        System.err.println("Credit amount " + credit + " is above the limit set to " + max + ".");
tutaj powinnas ustawic pole `message` przy uzyciu klasy nadrzednej

2020-05-11 07:58 UTC, beattaa commented on src/zajacia10/zadanie2/CashMachine.java
> +        try {
usuniety

2020-05-11 08:26 UTC, beattaa commented on src/zajacia10/zadanie2/CashMachine.java
> +        switch (getClientChoice()) {
poprawione

2020-05-11 08:58 UTC, pawel-javastart approved these changes

2020-05-14 07:47 UTC, merged